variables:
  KUBERNETES_CPU_LIMIT: "8"

stages:
  - test

go-tests:
  tags: [kata]
  stage: test
  image: golang:1.26.4-alpine
  before_script:
    - go mod download
    - apk add make npm
    - go generate ./...
  script:
    - go test -coverprofile=coverage.out ./...
  after_script:
    - go tool cover -html=coverage.out -o coverage.html
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - ./coverage.xml
      - ./coverage.out
      - ./coverage.html
