variables:
  KUBERNETES_CPU_LIMIT: "5"

stages:
  - test

go-tests:
  tags: [kata]
  stage: test
  image: golang:1.26.4-alpine
  before_script:
    - go mod download
    - apk add make npm
    - go generate ./...
  script:
    - go test -coverprofile=coverage.out ./...
  after_script:
    - go tool cover -html=coverage.out -o coverage.html
  artifacts:
    when: always
    paths:
      - ./coverage.out
      - ./coverage.html
