// Actual code generation, single file to enforce order

//go:generate rm -rf ../../generated
//go:generate sh -c "cd ../.. && npm exec @bufbuild/buf generate"
//go:generate go tool -C ../.. sqlc generate

// Mockery depends on other interfaces generated by sqlc

//go:generate go tool -C ../.. mockery

package codegen
