// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: servis/vseth/vis/messaging/messaging.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name to display when sending as sys user e.g. Admin. Due to technical
	// reasons it will always be the same sending address
	// i.e. the sending address needs to be 'sys_staging@vis.ethz.ch' (staging) or
	// 'sys_message_api@vis.ethz.ch' (production).
	// If you want to set a custom sending address e.g. '<appname>@vis.ethz.ch',
	// then you need to create a mailalias from '<appname>@vis.ethz.ch' to
	// 'sys_staging@vis.ethz.ch' (staging) or 'sys_message_api@vis.ethz.ch' (production)
	// respectively and set 'can_send' to true.
	From          string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ReplyTo       string   `protobuf:"bytes,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"` // What address to reply to. e.g. "LUK <luk@vis.ethz.ch>"
	To            []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`                          // List of to. Format: "Admin <root@vis.ethz.ch>" - will result in error if not provided
	Cc            []string `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`                          //  List of cc. Format: "Admin <root@vis.ethz.ch>"
	Bcc           []string `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`                        // List of bcc.
	Subject       string   `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`                // Subject of the message - will result in error if not provided
	Body          string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`                      // The content of the message - will result in error if not provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailRequest) Reset() {
	*x = MailRequest{}
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRequest) ProtoMessage() {}

func (x *MailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRequest.ProtoReflect.Descriptor instead.
func (*MailRequest) Descriptor() ([]byte, []int) {
	return file_servis_vseth_vis_messaging_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *MailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MailRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *MailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *MailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *MailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailResponse) Reset() {
	*x = MailResponse{}
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailResponse) ProtoMessage() {}

func (x *MailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailResponse.ProtoReflect.Descriptor instead.
func (*MailResponse) Descriptor() ([]byte, []int) {
	return file_servis_vseth_vis_messaging_messaging_proto_rawDescGZIP(), []int{1}
}

type SlackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Recipient:
	//
	//	*SlackRequest_UserEmail
	//	*SlackRequest_SlackUserId
	Recipient isSlackRequest_Recipient `protobuf_oneof:"recipient"`
	// JSON-encoded array of Slack blocks https://app.slack.com/block-kit-builder/
	BlocksJson string `protobuf:"bytes,2,opt,name=blocks_json,json=blocksJson,proto3" json:"blocks_json,omitempty"`
	// Fallback plain-text message
	FallbackText  string `protobuf:"bytes,3,opt,name=fallback_text,json=fallbackText,proto3" json:"fallback_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackRequest) Reset() {
	*x = SlackRequest{}
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackRequest) ProtoMessage() {}

func (x *SlackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackRequest.ProtoReflect.Descriptor instead.
func (*SlackRequest) Descriptor() ([]byte, []int) {
	return file_servis_vseth_vis_messaging_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *SlackRequest) GetRecipient() isSlackRequest_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *SlackRequest) GetUserEmail() string {
	if x != nil {
		if x, ok := x.Recipient.(*SlackRequest_UserEmail); ok {
			return x.UserEmail
		}
	}
	return ""
}

func (x *SlackRequest) GetSlackUserId() string {
	if x != nil {
		if x, ok := x.Recipient.(*SlackRequest_SlackUserId); ok {
			return x.SlackUserId
		}
	}
	return ""
}

func (x *SlackRequest) GetBlocksJson() string {
	if x != nil {
		return x.BlocksJson
	}
	return ""
}

func (x *SlackRequest) GetFallbackText() string {
	if x != nil {
		return x.FallbackText
	}
	return ""
}

type isSlackRequest_Recipient interface {
	isSlackRequest_Recipient()
}

type SlackRequest_UserEmail struct {
	// The email address used to look up the Slack user.
	UserEmail string `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3,oneof"`
}

type SlackRequest_SlackUserId struct {
	// The Slack user ID (if known).
	SlackUserId string `protobuf:"bytes,4,opt,name=slack_user_id,json=slackUserId,proto3,oneof"`
}

func (*SlackRequest_UserEmail) isSlackRequest_Recipient() {}

func (*SlackRequest_SlackUserId) isSlackRequest_Recipient() {}

type SlackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackResponse) Reset() {
	*x = SlackResponse{}
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackResponse) ProtoMessage() {}

func (x *SlackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servis_vseth_vis_messaging_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackResponse.ProtoReflect.Descriptor instead.
func (*SlackResponse) Descriptor() ([]byte, []int) {
	return file_servis_vseth_vis_messaging_messaging_proto_rawDescGZIP(), []int{3}
}

var File_servis_vseth_vis_messaging_messaging_proto protoreflect.FileDescriptor

const file_servis_vseth_vis_messaging_messaging_proto_rawDesc = "" +
	"\n" +
	"*servis/vseth/vis/messaging/messaging.proto\x12\x13vseth.vis.messaging\"\x9c\x01\n" +
	"\vMailRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x19\n" +
	"\breply_to\x18\x02 \x01(\tR\areplyTo\x12\x0e\n" +
	"\x02to\x18\x03 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x04 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x05 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\"\x0e\n" +
	"\fMailResponse\"\xa8\x01\n" +
	"\fSlackRequest\x12\x1f\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tH\x00R\tuserEmail\x12$\n" +
	"\rslack_user_id\x18\x04 \x01(\tH\x00R\vslackUserId\x12\x1f\n" +
	"\vblocks_json\x18\x02 \x01(\tR\n" +
	"blocksJson\x12#\n" +
	"\rfallback_text\x18\x03 \x01(\tR\ffallbackTextB\v\n" +
	"\trecipient\"\x0f\n" +
	"\rSlackResponse2\xb7\x01\n" +
	"\tMessaging\x12O\n" +
	"\bSendMail\x12 .vseth.vis.messaging.MailRequest\x1a!.vseth.vis.messaging.MailResponse\x12Y\n" +
	"\x10SendSlackMessage\x12!.vseth.vis.messaging.SlackRequest\x1a\".vseth.vis.messaging.SlackResponseB4\n" +
	"\x16ch.vseth.vis.messagingZ\x1aservis/vseth/vis/messagingb\x06proto3"

var (
	file_servis_vseth_vis_messaging_messaging_proto_rawDescOnce sync.Once
	file_servis_vseth_vis_messaging_messaging_proto_rawDescData []byte
)

func file_servis_vseth_vis_messaging_messaging_proto_rawDescGZIP() []byte {
	file_servis_vseth_vis_messaging_messaging_proto_rawDescOnce.Do(func() {
		file_servis_vseth_vis_messaging_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servis_vseth_vis_messaging_messaging_proto_rawDesc), len(file_servis_vseth_vis_messaging_messaging_proto_rawDesc)))
	})
	return file_servis_vseth_vis_messaging_messaging_proto_rawDescData
}

var file_servis_vseth_vis_messaging_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_servis_vseth_vis_messaging_messaging_proto_goTypes = []any{
	(*MailRequest)(nil),   // 0: vseth.vis.messaging.MailRequest
	(*MailResponse)(nil),  // 1: vseth.vis.messaging.MailResponse
	(*SlackRequest)(nil),  // 2: vseth.vis.messaging.SlackRequest
	(*SlackResponse)(nil), // 3: vseth.vis.messaging.SlackResponse
}
var file_servis_vseth_vis_messaging_messaging_proto_depIdxs = []int32{
	0, // 0: vseth.vis.messaging.Messaging.SendMail:input_type -> vseth.vis.messaging.MailRequest
	2, // 1: vseth.vis.messaging.Messaging.SendSlackMessage:input_type -> vseth.vis.messaging.SlackRequest
	1, // 2: vseth.vis.messaging.Messaging.SendMail:output_type -> vseth.vis.messaging.MailResponse
	3, // 3: vseth.vis.messaging.Messaging.SendSlackMessage:output_type -> vseth.vis.messaging.SlackResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servis_vseth_vis_messaging_messaging_proto_init() }
func file_servis_vseth_vis_messaging_messaging_proto_init() {
	if File_servis_vseth_vis_messaging_messaging_proto != nil {
		return
	}
	file_servis_vseth_vis_messaging_messaging_proto_msgTypes[2].OneofWrappers = []any{
		(*SlackRequest_UserEmail)(nil),
		(*SlackRequest_SlackUserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servis_vseth_vis_messaging_messaging_proto_rawDesc), len(file_servis_vseth_vis_messaging_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servis_vseth_vis_messaging_messaging_proto_goTypes,
		DependencyIndexes: file_servis_vseth_vis_messaging_messaging_proto_depIdxs,
		MessageInfos:      file_servis_vseth_vis_messaging_messaging_proto_msgTypes,
	}.Build()
	File_servis_vseth_vis_messaging_messaging_proto = out.File
	file_servis_vseth_vis_messaging_messaging_proto_goTypes = nil
	file_servis_vseth_vis_messaging_messaging_proto_depIdxs = nil
}
