// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: servis/self/messaging.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSlackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// JSON-encoded array of Slack Block Kit blocks
	BlocksJson string `protobuf:"bytes,2,opt,name=blocks_json,json=blocksJson,proto3" json:"blocks_json,omitempty"`
	// Fallback plain-text message
	FallbackText  string `protobuf:"bytes,3,opt,name=fallback_text,json=fallbackText,proto3" json:"fallback_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSlackRequest) Reset() {
	*x = SendSlackRequest{}
	mi := &file_servis_self_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSlackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSlackRequest) ProtoMessage() {}

func (x *SendSlackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servis_self_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSlackRequest.ProtoReflect.Descriptor instead.
func (*SendSlackRequest) Descriptor() ([]byte, []int) {
	return file_servis_self_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *SendSlackRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendSlackRequest) GetBlocksJson() string {
	if x != nil {
		return x.BlocksJson
	}
	return ""
}

func (x *SendSlackRequest) GetFallbackText() string {
	if x != nil {
		return x.FallbackText
	}
	return ""
}

type SendSlackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSlackResponse) Reset() {
	*x = SendSlackResponse{}
	mi := &file_servis_self_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSlackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSlackResponse) ProtoMessage() {}

func (x *SendSlackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servis_self_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSlackResponse.ProtoReflect.Descriptor instead.
func (*SendSlackResponse) Descriptor() ([]byte, []int) {
	return file_servis_self_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *SendSlackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSlackResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_servis_self_messaging_proto protoreflect.FileDescriptor

const file_servis_self_messaging_proto_rawDesc = "" +
	"\n" +
	"\x1bservis/self/messaging.proto\x12\tmessaging\"n\n" +
	"\x10SendSlackRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1f\n" +
	"\vblocks_json\x18\x02 \x01(\tR\n" +
	"blocksJson\x12#\n" +
	"\rfallback_text\x18\x03 \x01(\tR\ffallbackText\"C\n" +
	"\x11SendSlackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Z\n" +
	"\tMessenger\x12M\n" +
	"\x10SendSlackMessage\x12\x1b.messaging.SendSlackRequest\x1a\x1c.messaging.SendSlackResponseBXZVgitlab.ethz.ch/vseth/1100-fv/1116-vis/cat/sip-vis-cat-apps/2message2api/internal/pb;pbb\x06proto3"

var (
	file_servis_self_messaging_proto_rawDescOnce sync.Once
	file_servis_self_messaging_proto_rawDescData []byte
)

func file_servis_self_messaging_proto_rawDescGZIP() []byte {
	file_servis_self_messaging_proto_rawDescOnce.Do(func() {
		file_servis_self_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servis_self_messaging_proto_rawDesc), len(file_servis_self_messaging_proto_rawDesc)))
	})
	return file_servis_self_messaging_proto_rawDescData
}

var file_servis_self_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_servis_self_messaging_proto_goTypes = []any{
	(*SendSlackRequest)(nil),  // 0: messaging.SendSlackRequest
	(*SendSlackResponse)(nil), // 1: messaging.SendSlackResponse
}
var file_servis_self_messaging_proto_depIdxs = []int32{
	0, // 0: messaging.Messenger.SendSlackMessage:input_type -> messaging.SendSlackRequest
	1, // 1: messaging.Messenger.SendSlackMessage:output_type -> messaging.SendSlackResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servis_self_messaging_proto_init() }
func file_servis_self_messaging_proto_init() {
	if File_servis_self_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servis_self_messaging_proto_rawDesc), len(file_servis_self_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servis_self_messaging_proto_goTypes,
		DependencyIndexes: file_servis_self_messaging_proto_depIdxs,
		MessageInfos:      file_servis_self_messaging_proto_msgTypes,
	}.Build()
	File_servis_self_messaging_proto = out.File
	file_servis_self_messaging_proto_goTypes = nil
	file_servis_self_messaging_proto_depIdxs = nil
}
