// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: servis/self/messaging.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_servis_self_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servis_self_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_servis_self_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_servis_self_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servis_self_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_servis_self_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_servis_self_messaging_proto protoreflect.FileDescriptor

const file_servis_self_messaging_proto_rawDesc = "" +
	"\n" +
	"\x1bservis/self/messaging.proto\x12\tmessaging\"7\n" +
	"\vSendRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\">\n" +
	"\fSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2K\n" +
	"\tMessenger\x12>\n" +
	"\vSendMessage\x12\x16.messaging.SendRequest\x1a\x17.messaging.SendResponseBXZVgitlab.ethz.ch/vseth/1100-fv/1116-vis/cat/sip-vis-cat-apps/2message2api/internal/pb;pbb\x06proto3"

var (
	file_servis_self_messaging_proto_rawDescOnce sync.Once
	file_servis_self_messaging_proto_rawDescData []byte
)

func file_servis_self_messaging_proto_rawDescGZIP() []byte {
	file_servis_self_messaging_proto_rawDescOnce.Do(func() {
		file_servis_self_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servis_self_messaging_proto_rawDesc), len(file_servis_self_messaging_proto_rawDesc)))
	})
	return file_servis_self_messaging_proto_rawDescData
}

var file_servis_self_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_servis_self_messaging_proto_goTypes = []any{
	(*SendRequest)(nil),  // 0: messaging.SendRequest
	(*SendResponse)(nil), // 1: messaging.SendResponse
}
var file_servis_self_messaging_proto_depIdxs = []int32{
	0, // 0: messaging.Messenger.SendMessage:input_type -> messaging.SendRequest
	1, // 1: messaging.Messenger.SendMessage:output_type -> messaging.SendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servis_self_messaging_proto_init() }
func file_servis_self_messaging_proto_init() {
	if File_servis_self_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servis_self_messaging_proto_rawDesc), len(file_servis_self_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servis_self_messaging_proto_goTypes,
		DependencyIndexes: file_servis_self_messaging_proto_depIdxs,
		MessageInfos:      file_servis_self_messaging_proto_msgTypes,
	}.Build()
	File_servis_self_messaging_proto = out.File
	file_servis_self_messaging_proto_goTypes = nil
	file_servis_self_messaging_proto_depIdxs = nil
}
